kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-pvc
  # Set this annotation to NOT let Kubernetes automatically create
  # a persistent volume for this volume claim.
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
  selector:
    # To make sure we match the claim with the exact volume, match the label
    matchLabels:
      usage: test-label