apiVersion: v1
kind: Pod
metadata:
 name: mount-test-smb
spec:
  containers:
    - image: aliakbarrehman/jupyterhub:latest
      name: deployment-smb
      volumeMounts:
        - name: smb
          mountPath: "/mnt/smb"
          readOnly: false
  volumes:
    - name: smb
      persistentVolumeClaim:
        claimName: uio-pvc