kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ volumeClaim['name'] }}-pvc
  # Set this annotation to NOT let Kubernetes automatically create
  # a persistent volume for this volume claim.
  annotations:
    volume.beta.kubernetes.io/storage-class: ""
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ volumeClaim['size'] }}
  selector:
    # To make sure we match the claim with the exact volume, match the label
    matchLabels:
      usage: {{ volumeClaim['usage'] }}