apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ volume['name'] }}-pv
spec:
  capacity:
    storage: {{ volume['size'] }}
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: smb
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
  csi:
    driver: smb.csi.k8s.io
    readOnly: true
    volumeHandle: {{ volume['usage'] }}  # make sure it's a unique id in the cluster
    volumeAttributes:
      source: //{{ volume['storageAccountName'] }}.file.core.windows.net/{{ volume['shareName'] }}
    nodeStageSecretRef:
      name: {{ volume['secret'] }}
      namespace: {{ volume['secretNamespace'] }}