apiVersion: v1
kind: Secret
metadata:
  name: test-secret
type: Opaque
data:
  azurestorageaccountname: ZGF0YXNoYXJpbmd0ZXN0c3RvcmFnZQ==
  azurestorageaccountkey: LzRncVhkTHdVMU44TDJ3dndmSjlRSDFaTUZqRE95UkFFbDE5cjZ1VXhlVkdtS3RlN2dOZy9UbHp6RVVqTXdjN0JFUTAyVm5sNDVJNENaYXh1cm43Q3c9PQ==