apiVersion: v1
kind: PersistentVolume
metadata:
  name: test-pv
  # The label is used for matching the exact claim
  labels:
    usage: test-label
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadOnlyMany
  # persistentVolumeReclaimPolicy: Retain
  azureFile:
    # Replace with your secret name
    secretName: test-secret
    # Replace with correct storage share name
    shareName: uio-azure
    # In case the secret is stored in a different namespace
    secretNamespace: jhub
    readOnly: true